name: Build

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      repo_tags: ${{ steps.repo-tags.outputs.repo_tags }}
      upstream_ver: ${{ steps.upstream-ver.outputs.upstream_ver }}
    steps:
      - name: Get repo tags
        id: repo-tags
        run: |
          {
            echo 'repo_tags<<EOF'
            gh api /repos/$GITHUB_REPOSITORY/releases | jq '.[].tag_name'
            echo EOF
          } >> "$GITHUB_ENV"
          {
            echo 'repo_tags<<EOF'
            gh api /repos/$GITHUB_REPOSITORY/releases | jq '.[].tag_name'
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Get upstream version
        id: upstream-ver
        run: |
          curl -SL 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=eternalterminal' -o "PKGBUILD"
          . "PKGBUILD"
          echo "upstream_ver=${pkgver}-${pkgrel}" >> "$GITHUB_ENV"
          echo "upstream_ver=${pkgver}-${pkgrel}" >> "$GITHUB_OUTPUT"
      - name: Check if build exist
        id: build-exist
        run: |
          if echo "$repo_tags" | grep -q "$upstream_ver"; then
            echo "build exist"
          else
            echo "build does not exist"
          fi
  build_and_release:
    needs: test
    if: ${{ ! contains(needs.test.outputs.repo_tags, upstream_ver) }}
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v4
      - name: Echo
        run: |
          echo "Build does not exist"
          echo ${{ needs.test.outputs.repo_tags }}
          echo ${{ needs.test.outputs.upstream_ver }}
