name: Build

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      repo_tags: ${{ steps.repo-tags.outputs.repo_tags }}
      upstream_ver: ${{ steps.upstream-ver.outputs.upstream_ver }}
    steps:
      - name: Get repo tags
        id: repo-tags
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          {
            echo 'repo_tags<<EOF'
            gh api /repos/$GITHUB_REPOSITORY/releases | jq '.[].tag_name'
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Get upstream version
        id: upstream-ver
        run: |
          curl -SL 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=eternalterminal' -o "PKGBUILD"
          . "PKGBUILD"
          echo "upstream_ver=${pkgver}-${pkgrel}" >> "$GITHUB_OUTPUT"
  build_and_release:
    needs: test
    if: ${{ ! contains(needs.test.outputs.repo_tags, needs.test.outputs.upstream_ver) }}
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install git
        run: |
          pacman -Syu --noconfirm git
      - name: Clone repo
        run: |
          git clone 'https://aur.archlinux.org/eternalterminal.git'
      - name: Build
        working-directory: ./eternalterminal
        # Enable root to run makepkg
        run: |
          sed -i '/E_ROOT/d' /usr/bin/makepkg
          sed -i 's/ debug / !debug /g' /etc/makepkg.conf
          makepkg -s --noconfirm
      - name: Generate hashsums
        working-directory: ./eternalterminal
        run: |
          sha256sum *.zst > SHA256SUMS
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{needs.test.outputs.upstream_ver}}
          body: ${{needs.test.outputs.upstream_ver}}
          commit: main
          makeLatest: true
          artifacts: "./eternalterminal/*.zst,./eternalterminal/SHA256SUMS"
