name: Build

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      upstream_ver: ${{ steps.upstream-ver.outputs.upstream_ver }}
      repo_ver: ${{ steps.repo-ver.outputs.repo_ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check latest tag
        id: repo-ver
        run: |
          repo_ver="$(git tag --sort=committerdate | tail -1)"
          echo "repo_ver=${repo_ver}" >> "$GITHUB_OUTPUT"
      - name: Clone repo
        run: |
          git clone 'https://aur.archlinux.org/eternalterminal.git'
      - name: Check upstream version
        id: upstream-ver
        working-directory: ./eternalterminal
        run: |
          pkgver=$(grep -oP "^pkgver='?\K[\d\.]+" './PKGBUILD')
          pkgrel="$(grep -oP "^pkgrel=\K\d+" './PKGBUILD')"
          echo "upstream_ver=${pkgver}-${pkgrel}" >> "$GITHUB_OUTPUT"
  build_and_release:
    needs: test
    if: needs.test.outputs.upstream_ver != needs.test.outputs.repo_ver
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install git
        run: |
          pacman -Syu --noconfirm git
      - name: Clone repo
        run: |
          git clone 'https://aur.archlinux.org/eternalterminal.git'
      - name: Build
        working-directory: ./eternalterminal
        # Enable root to run makepkg
        run: |
          sed -i '/E_ROOT/d' /usr/bin/makepkg
          sed -i 's/ debug / !debug /g' /etc/makepkg.conf
          makepkg -s --noconfirm
      - name: Generate hashsums
        working-directory: ./eternalterminal
        run: |
          sha256sum *.zst > SHA256SUMS
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{needs.test.outputs.upstream_ver}}
          body: ${{needs.test.outputs.upstream_ver}}
          commit: main
          makeLatest: true
          artifacts: "./eternalterminal/*.zst,./eternalterminal/SHA256SUMS"
